

DROP TABLE IF EXISTS public.business;

CREATE TABLE IF NOT EXISTS public.business
(
    id integer NOT NULL DEFAULT nextval('business_id_seq'::regclass),
    type character varying(200) COLLATE pg_catalog."default" NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    street character varying(200) COLLATE pg_catalog."default" NOT NULL,
    zip_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    state character varying(2) COLLATE pg_catalog."default" NOT NULL,
    qb_vendor_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    qb_city_state_zip character varying(500) COLLATE pg_catalog."default" NOT NULL,
    primary_phone character varying(10) COLLATE pg_catalog."default" NOT NULL,
    backup_phone character varying(10) COLLATE pg_catalog."default",
    primary_email character varying(256) COLLATE pg_catalog."default" NOT NULL,
    comments character varying(200) COLLATE pg_catalog."default",
    fax_phone character varying(10) COLLATE pg_catalog."default",
    contact_name character varying(100) COLLATE pg_catalog."default",
    website character varying(200) COLLATE pg_catalog."default",
    business_hours character varying(500) COLLATE pg_catalog."default" NOT NULL,
    find_out character varying(200) COLLATE pg_catalog."default",
    onboarding_status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    join_date date NOT NULL,
    input_type_status character varying(200) COLLATE pg_catalog."default",
    vendor_type character varying(200) COLLATE pg_catalog."default",
    status character varying(200) COLLATE pg_catalog."default",
    pets_of_the_homeless_discount boolean,
    updated_by character varying(200) COLLATE pg_catalog."default",
    updated_date_time date,
    sync_to_qb boolean,
    veterinary boolean NOT NULL,
    ressoure boolean NOT NULL,
    food boolean NOT NULL,
    donation boolean NOT NULL,
    family_shelter boolean NOT NULL,
    wellness boolean NOT NULL,
    spay_neuter boolean NOT NULL,
    financial boolean NOT NULL,
    re_home boolean NOT NULL,
    er_boarding boolean NOT NULL,
    senior boolean NOT NULL,
    cancer boolean NOT NULL,
    dog boolean NOT NULL,
    cat boolean NOT NULL,
    fph_phone character varying(200) COLLATE pg_catalog."default",
    contact_phone character varying(20) COLLATE pg_catalog."default",
    web_notes character varying(200) COLLATE pg_catalog."default",
    internal_notes character varying(5000) COLLATE pg_catalog."default",
    published boolean NOT NULL,
    shelter boolean NOT NULL,
    domestic_violence boolean NOT NULL,
    web_date_init date,
    ent_qb boolean NOT NULL,
    service_request boolean NOT NULL,
    inactive boolean NOT NULL,
    final_check boolean NOT NULL,
    created_by character varying COLLATE pg_catalog."default",
    created_date date,
    city character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT business_pkey PRIMARY KEY (id)
)
